### ISSUE TITLE
Gotta solve for using files in the personas ( for specifying large returns for example in the params )

### ISSUE THREAD

**Issue by JeremyCroff** [intuit/saloon#20]
currently I have it implemented with passing in the resource to the definition 
```body : (data, params) => return = taxReturnLookUpMap[params.return]```

**Comment by jwils0n** [comment]
I think that's more of an implementation problem to solve from whatever is consuming saloon. Our examples use static JSON files. There's nothing to say that you couldn't use dynamic JS modules that return objects.

**Comment by JeremyCroff** [comment]
It would be nice to have it baked in to the tool so that the consumer does not have to solve for it.
